# This file was generated by GoReleaser. DO NOT EDIT.
class Kuronekocat < Formula
  desc "Kuroneko Yamato Tracking Wrapper Tool"
  homepage "https://github.com/anatofuz/kuronekocat"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/AnaTofuZ/kuronekocat/releases/download/v1.0.1/kuronekocat_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "856d3946c440b9bb77b3a97892d562a218701d0e3d88c1ca38a60345a40c6749"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/AnaTofuZ/kuronekocat/releases/download/v1.0.1/kuronekocat_1.0.1_Linux_x86_64.tar.gz"
    sha256 "925c7558c06093cf9a92f1e50adc5d76556d508866f0ac02d10a98b8cc56f511"
  end

  def install
    bin.install "kuronekocat"
  end
end
