# This file was generated by GoReleaser. DO NOT EDIT.
class Kuronekocat < Formula
  desc "Kuroneko Yamato Tracking Wrapper Tool"
  homepage "https://github.com/anatofuz/kuronekocat"
  version "1.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/AnaTofuZ/kuronekocat/releases/download/v1.1.0/kuronekocat_1.1.0_Darwin_x86_64.tar.gz"
    sha256 "7ce9d9ef7e847a7c14a0f3ab2d11810a49ab1a3159a0cc97f5eed683dfcbf24a"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/AnaTofuZ/kuronekocat/releases/download/v1.1.0/kuronekocat_1.1.0_Linux_x86_64.tar.gz"
    sha256 "c043e177e052560322889e6a61d1710eb8c3069472e85941cc3d2c7e56b0c0f1"
  end

  def install
    bin.install "kuronekocat"
  end
end
